### ISSUE TITLE
#INC-5312: Missing image

### ISSUE THREAD

**Issue by vanessa-cooper** [ObelusFamily/Anythink-Market-pr8f6#3]
Cool! Now, It seems that when creating a new product without an image, there are broken images showing up in the product catalog. Please fix this by replicating this bug locally with mock data.
Take a screenshot of the fix and attach it to a PR when you close the bug. There's a placeholder image in the repo that you can use named `placeholder.png`

**Comment by Hindol19** [comment]
![pl2](https://user-images.githubusercontent.com/108117454/182458249-a7155c4e-bab4-474a-95f5-45adddf65f19.png)

**Comment by Hindol19** [comment]
![pl2](https://user-images.githubusercontent.com/108117454/182566110-a01a70e3-0582-47ac-9cac-f99e77b1549d.png)
